/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "surface": "#0a0e17",
        "error": "#ffb4ab",
        "secondary-fixed": "#6ffbbe",
        "outline-variant": "#44474e",
        "on-background": "#e2e2e9",
        "on-secondary-fixed-variant": "#005236",
        "inverse-on-surface": "#2d3133",
        "primary-container": "#1e293b",
        "on-tertiary-fixed": "#d8e2ff",
        "surface-variant": "#1e2433",
        "primary-fixed": "#dae2fd",
        "on-surface": "#e2e2e9",
        "on-secondary-container": "#6ffbbe",
        "outline": "#8e9099",
        "primary": "#bec6e0",
        "on-secondary": "#003825",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-fixed-variant": "#bec6e0",
        "surface-container-high": "#232938",
        "on-primary-fixed": "#dae2fd",
        "on-surface-variant": "#c4c6cf",
        "surface-container-lowest": "#111827",
        "tertiary-fixed": "#d8e2ff",
        "surface-container-low": "#151b28",
        "on-tertiary": "#002f6c",
        "inverse-surface": "#e2e2e9",
        "on-tertiary-fixed-variant": "#adc6ff",
        "inverse-primary": "#3f465c",
        "surface-container": "#1a2030",
        "surface-bright": "#2d3442",
        "secondary-container": "#005236",
        "secondary": "#4edea3",
        "background": "#0a0e17",
        "primary-fixed-dim": "#bec6e0",
        "surface-dim": "#0a0e17",
        "on-tertiary-container": "#adc6ff",
        "surface-container-highest": "#2d3442",
        "on-primary": "#282e3d",
        "tertiary-fixed-dim": "#adc6ff",
        "tertiary-container": "#004395",
        "on-error": "#690005",
        "on-secondary-fixed": "#002113",
        "on-error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "16px",
        "xl": "32px",
        "base": "4px",
        "lg": "24px",
        "2xl": "48px",
        "container-padding": "20px",
        "md": "16px",
        "sm": "8px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "display-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "display-md": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "display-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
