/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface": "#f7f9fb",
        "error": "#ba1a1a",
        "secondary-fixed": "#6ffbbe",
        "outline-variant": "#c6c6cd",
        "on-background": "#191c1e",
        "on-secondary-fixed-variant": "#005236",
        "inverse-on-surface": "#eff1f3",
        "primary-container": "#131b2e",
        "on-tertiary-fixed": "#001a42",
        "surface-variant": "#e0e3e5",
        "primary-fixed": "#dae2fd",
        "on-surface": "#191c1e",
        "on-secondary-container": "#00714d",
        "outline": "#76777d",
        "primary": "#000000",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container-high": "#e6e8ea",
        "on-primary-fixed": "#131b2e",
        "on-surface-variant": "#45464d",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#d8e2ff",
        "surface-container-low": "#f2f4f6",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed-variant": "#004395",
        "inverse-primary": "#bec6e0",
        "surface-container": "#eceef0",
        "surface-bright": "#f7f9fb",
        "secondary-container": "#6cf8bb",
        "secondary": "#006c49",
        "background": "#f7f9fb",
        "primary-fixed-dim": "#bec6e0",
        "surface-dim": "#d8dadc",
        "on-tertiary-container": "#3980f4",
        "surface-container-highest": "#e0e3e5",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#adc6ff",
        "tertiary-container": "#001a42",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#002113"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "16px",
        "xl": "32px",
        "base": "4px",
        "lg": "24px",
        "2xl": "48px",
        "container-padding": "20px",
        "md": "16px",
        "sm": "8px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "display-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "display-md": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "display-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
